// Generated by the protoc-gen-objcmtl plugin.
// source: hello.proto
#import "Hello.h"


@implementation XYHello

+ (NSValueTransformer *)greetingJSONTransformer {
    return [NSValueTransformer mtl_valueMappingTransformerWithDictionary:@{
       @"NONE": @(NONE),
       @"MR": @(MR),
       @"MRS": @(MRS),
       @"MISS": @(MISS)
      }];
    }
+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return @{
        @"greeting": @"greeting",
        @"name": @"name"
      };
}
@end
