// Generated by the protoc-gen-objcmtl plugin.
// source: hello.proto
#import <Mantle/Mantle.h>
typedef enum : NSUInteger {
   NONE = 0,
   MR = 1,
   MRS = 2,
   MISS = 3
} XYGreeting;

@class XYHello;

@interface XYHello : MTLModel <MTLJSONSerializing>
@property XYGreeting greeting;
@property NSString *name;
@end
